jwt:
  secret: 213asd21sad21dads21das2d21d3af4faf13f4g56h6k3f
  lifetime: 30m


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/todo
    username: postgres
    password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: tt7545946@gmail.com
    password: arngzzalhxbcjbnd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


spring.flyway:
  validate-migration-naming: true
  url: jdbc:postgresql://localhost:5432/todo
  user: postgres
  password: 123456
  enabled: true
  locations:
    - 'classpath:db/migration'
springdoc:
  api-docs:
    enabled: true
